### ISSUE TITLE
关于插入图片标签没有设置大小的问题

### ISSUE THREAD

**Issue by fly7632785** [huzhenjie/RichTextEditor#1]
你好，你的库，很不错。
我在用的时候，发现最终生成的html标签，对于图片而言，貌似是没有插入width height属性的。
导致，webview解析显示的时候 图片是原图大小。
我也正准备想办法把这个问题解决一下

**Comment by huzhenjie** [comment]
不知道是否能够解决您的问题，已在img标签加入width=100%的设置

code:

[8ac4ad5](https://github.com/huzhenjie/RichTextEditor/commit/504c2a40c37171677edf1e87b3941bdd0021091f)

可以通过这个方式显示生成的html

```
fromHtml(yourHtmlStr)
```

------

另：你还可以通过此方式加入到你的工程

```
dependencies {
    compile 'com.github.huzhenjie:RichTextEditor:1.0.2'
}
```

具体方法可以参考 [README.md](https://github.com/huzhenjie/RichTextEditor/blob/master/README.md)


**期待你的回复**

**Comment by fly7632785** [comment]
谢谢  ，已经OK了 
还有一个提一下
![000a3c47-bf88-42bc-a964-0f8c9d8591c6](https://cloud.githubusercontent.com/assets/10276266/24441354/cd70dedc-148b-11e7-9b07-592b8c08970e.png)
可以在图片插入后面加一个空行
