### ISSUE TITLE
大图片容易OOM，建议压缩，1.0.3版本插入图片会显示两张（android 4.4）

### ISSUE THREAD

**Issue by TTHHR** [huzhenjie/RichTextEditor#6]
如题。我压缩后的图片路径转Uri，传给rechText.image(uri,width)会解析失败。

**Comment by huzhenjie** [comment]
请提供一下 uri

**Comment by TTHHR** [comment]
image uri: content://com.android.providers.media.documents/document/image%3A9831
压缩后：zip image uri: /storage/emulated/0/Android/data/cn.atd3.code4a/cache/luban_disk_cache/1518314225949555.jpg

详细报错请看：http://blog.qingyuyu.cn/read.php/re-richtext/

**Comment by TTHHR** [comment]
1.0.3插入一张图，会显示两张，也在这个链接里

**Comment by huzhenjie** [comment]
## 关于 uri 的问题

> 请使用这种方式获取uri

```
Uri.fromFile(new File(yourLocalFilePath))
```

详见：

[https://stackoverflow.com/questions/32332003/glide-load-local-image-by-uri](https://stackoverflow.com/questions/32332003/glide-load-local-image-by-uri)

**Comment by TTHHR** [comment]
。。忘记了，是要用fromFile
图片显示依然是那个问题，不知道是不是手机的问题，1.0.2插入图片正常显示但是html有时会没有图。1.0.3插入图片会显示两张，HTML里倒是只有一张

**Comment by huzhenjie** [comment]
fix

试试 1.0.4 版本

另外：图片方面，推荐使用上传成功后的图片URL插入

**Comment by TTHHR** [comment]
好的，谢谢
