### ISSUE TITLE
关于，插入图片和上传图片

### ISSUE THREAD

**Issue by fly7632785** [huzhenjie/RichTextEditor#9]
你好，首先谢谢开源这个库给我们大家使用。
其次，有关于插入图片和上传图片的问题想请教一下。
我们从手机选择选择图片之后，库所做的是image(Uri)插入图片，然后展示的是本地的图片。
而我们使用富文本的逻辑是，选择了图片之后，立即上传到服务器，然后返回一个url地址。
所以，我期望的是把图片的url插入其中（glide可以展示出来），然后最后获取的html表情的img src就是一个url.
但是现在好像不支持这样做，请指点一二。

**Comment by huzhenjie** [comment]
很高兴看到非常有礼貌的提问！

你可以考虑把上传成功的url，通过 ` Uri.parse` 转成uri

然后 `richEditText.image(imageUri);`

**Comment by fly7632785** [comment]
十分感谢，看了下源码  的确可以如何。
